
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CRD.Dominio.Modelo.Entidades
{

    using System;
    using System.Collections.Generic;

    public partial class CRD_Iva
    {

        public int IdIva { get; set; }

        public int ValorIva { get; set; }

        public bool Activo { get; set; }

    }

}
