//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRD.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRD_BitacoraHistorico
    {
        public int ID { get; set; }
        public string Bienes_Recibidos { get; set; }
        public string Ciudad { get; set; }
        public string Origen_Documento { get; set; }
        public string Empresa { get; set; }
        public string Estado { get; set; }
        public string Factura { get; set; }
        public string Fecha_Emision { get; set; }
        public string Fecha_Recepcion_CRD { get; set; }
        public string Iva { get; set; }
        public string Largo_F { get; set; }
        public string Largo_O { get; set; }
        public string Responsable { get; set; }
        public string Motivo_Rechazo { get; set; }
        public string Nom_Proveedor { get; set; }
        public string Numero_Orden { get; set; }
        public string Observaciones { get; set; }
        public string Operador { get; set; }
        public string Valija_Origen { get; set; }
        public string Partner { get; set; }
        public string ProveedorTipo_Proveedor { get; set; }
        public string Referencia { get; set; }
        public string valija_Remitente { get; set; }
        public string Valija_Obs { get; set; }
        public string Ruc { get; set; }
        public string Sistema_Origen { get; set; }
        public string Status_Documentos { get; set; }
        public string Valor { get; set; }
        public string Usuario_edita { get; set; }
        public string Fecha_edita { get; set; }
        public string Indices_editados { get; set; }
        public string TipodeDocumento { get; set; }
        public string Caja_Paquete { get; set; }
        public string Cod_Empresa { get; set; }
        public string Tipo_Orden { get; set; }
        public string Cod_Pago { get; set; }
        public string Version_Registro { get; set; }
        public string Adicional_2 { get; set; }
        public string Adicional_3 { get; set; }
    }
}
