
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CRD.Dominio.Modelo.Entidades
{

    using System;
    using System.Collections.Generic;

    public partial class CRD_Valijas
    {

        public int IdValija { get; set; }
        public int IdBitacora { get; set; }

        public System.DateTime Fecha { get; set; }

        public string Origen { get; set; }

        public string Remitente { get; set; }

        public string Centro { get; set; }

        public string OBSV { get; set; }

        public bool Activo { get; set; }



        public virtual CRD_Bitacora CRD_Bitacora { get; set; }

    }

}
