//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRD.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRD_UsuarioRoles
    {
        public int IdUsuarioRoles { get; set; }
        public int UserId { get; set; }
        public int RoleId { get; set; }
    
        public virtual CRD_Roles CRD_Roles { get; set; }
        public virtual CRD_Usuarios CRD_Usuarios { get; set; }
    }
}
