
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CRD.Dominio.Modelo.Entidades
{

    using System;
    using System.Collections.Generic;

    public partial class CRD_EstadoTipoProcesos
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRD_EstadoTipoProcesos()
        {

            this.CRD_AnalistasCRD_EstadoTipoProcesos = new HashSet<CRD_AnalistasCRD_EstadoTipoProcesos>();

            this.CRD_Bitacora = new HashSet<CRD_Bitacora>();

        }


        public int IdEstadoTipoProceso { get; set; }

        public string Nombre { get; set; }

        public string Descripcion { get; set; }

        public bool Activo { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<CRD_AnalistasCRD_EstadoTipoProcesos> CRD_AnalistasCRD_EstadoTipoProcesos { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<CRD_Bitacora> CRD_Bitacora { get; set; }

    }

}
