//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRD.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRD_Bitacora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRD_Bitacora()
        {
            this.CRD_Valijas = new HashSet<CRD_Valijas>();
        }
    
        public int IdBitacora { get; set; }
        public string NumeroDocumentoPago { get; set; }
        public Nullable<bool> EstadoBienesRecibidos { get; set; }
        public Nullable<System.DateTime> FechaEmisionDocumento { get; set; }
        public Nullable<System.DateTime> FechaRecepcionDocumento { get; set; }
        public Nullable<decimal> IvaDocumento { get; set; }
        public int IdAnalista { get; set; }
        public string Observaciones { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public string TipoOrden { get; set; }

        public int IdTipoDocumentoPago { get; set; }
        public int IdTipoDocumento { get; set; }

        public int IdEstadoProceso { get; set; }

        public virtual CRD_Usuarios CRD_Usuarios { get; set; }
        public virtual CRD_Empresas CRD_Empresas { get; set; }
        public virtual CRD_Ordenes CRD_Ordenes { get; set; }
        public virtual CRD_Paquetes CRD_Paquetes { get; set; }
        public virtual CRD_Proveedores CRD_Proveedores { get; set; }
        public virtual CRD_TipoDocumentos CRD_TipoDocumentos { get; set; }
        public virtual CRD_TipoDocumentoPagos CRD_TipoDocumentoPagos { get; set; }
        public virtual CRD_EstadoTipoProcesos CRD_EstadoTipoProcesos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRD_Valijas> CRD_Valijas { get; set; }
    }
}
