//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRD.Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRD_Ordenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRD_Ordenes()
        {
            this.CRD_Bitacora = new HashSet<CRD_Bitacora>();
        }
    
        public string ID { get; set; }
        public string Tipo_Orden { get; set; }
        public string CodigoCompania { get; set; }
        public string CodigoSistema { get; set; }
        public string CodigoServicio { get; set; }
        public string Proceso { get; set; }
        public string Resultado { get; set; }
        public string Estado { get; set; }
        public string Error { get; set; }
        public string FechaProceso { get; set; }
        public string Id1 { get; set; }
        public string NumeroOrden { get; set; }
        public string CodTipoOrden { get; set; }
        public string Referencia { get; set; }
        public string Facturado { get; set; }
        public string Liberado { get; set; }
        public string Divisa { get; set; }
        public string TipoCambio { get; set; }
        public string Proveedor { get; set; }
        public string DescProveedor { get; set; }
        public string CodOrganizacion { get; set; }
        public string DesOrganizacion { get; set; }
        public string Compania { get; set; }
        public string DesCompania { get; set; }
        public string CodOrganizacionComp { get; set; }
        public string DesOrganizacionComp { get; set; }
        public string ImporteBruto { get; set; }
        public string Subtotal { get; set; }
        public string Iva { get; set; }
        public string ImporteNetoFacturado { get; set; }
        public string NetoEntregado { get; set; }
        public string IdentPropietario { get; set; }
        public string CodPropietario { get; set; }
        public string NombrePropietario { get; set; }
        public string IdentComprador { get; set; }
        public string CodComprador { get; set; }
        public string NombreComprador { get; set; }
        public string FechaOrden { get; set; }
        public string FechaPlanificadaRecepcion { get; set; }
        public string FechaRealRecepcion { get; set; }
        public string EstadoRecupDatos { get; set; }
        public string Texto1 { get; set; }
        public string Texto2 { get; set; }
        public string Texto3 { get; set; }
        public string Texto4 { get; set; }
        public string Texto5 { get; set; }
        public string Texto6 { get; set; }
        public string Texto7 { get; set; }
        public string Texto8 { get; set; }
        public string Texto9 { get; set; }
        public string Texto10 { get; set; }
        public string Numerico1 { get; set; }
        public string Numerico2 { get; set; }
        public string Numerico3 { get; set; }
        public string Numerico4 { get; set; }
        public string Numerico5 { get; set; }
        public string Fecha1 { get; set; }
        public string Fecha2 { get; set; }
        public string Fecha3 { get; set; }
        public string Fecha4 { get; set; }
        public string Fecha5 { get; set; }
        public string PersonaReferencia { get; set; }
        public string CodProveedorPrincipal { get; set; }
        public string NombreProveedorPrincipal { get; set; }
        public string BienesFacturadosRecib { get; set; }
        public string Id2 { get; set; }
        public string IdOrden { get; set; }
        public string NumeroOrden3 { get; set; }
        public string Posicion { get; set; }
        public string Facturado4 { get; set; }
        public string Liberado5 { get; set; }
        public string CantidadPedida { get; set; }
        public string UnidadCompra { get; set; }
        public string Precio { get; set; }
        public string Importe { get; set; }
        public string UnidadPrecio { get; set; }
        public string ImporteBruto6 { get; set; }
        public string Iva7 { get; set; }
        public string CodFiscal { get; set; }
        public string PorcentajeIva { get; set; }
        public string ImporteNetoFacturado8 { get; set; }
        public string CantidadFacturada { get; set; }
        public string CantidadNetaEntregada { get; set; }
        public string CantidadEntregada { get; set; }
        public string EntregaMercaderiaReq { get; set; }
        public string CodProducto { get; set; }
        public string NombreProducto { get; set; }
        public string Unspsc { get; set; }
        public string FechaPlanificadaRecepcion9 { get; set; }
        public string FechaRealRecepcion10 { get; set; }
        public string Comentario { get; set; }
        public string Texto111 { get; set; }
        public string Texto212 { get; set; }
        public string Texto313 { get; set; }
        public string Texto414 { get; set; }
        public string Texto515 { get; set; }
        public string Texto616 { get; set; }
        public string Texto717 { get; set; }
        public string Texto818 { get; set; }
        public string Texto919 { get; set; }
        public string Texto1020 { get; set; }
        public string Numerico121 { get; set; }
        public string Numerico222 { get; set; }
        public string Numerico323 { get; set; }
        public string Numerico424 { get; set; }
        public string Numerico525 { get; set; }
        public string Fecha126 { get; set; }
        public string Fecha227 { get; set; }
        public string Fecha328 { get; set; }
        public string Fecha429 { get; set; }
        public string Fecha530 { get; set; }
        public string Descripcion { get; set; }
        public string CodFactorIng { get; set; }
        public string CodEstrategiaIng { get; set; }
        public string BienesFacturadosRecib31 { get; set; }
        public string MetodoRecepcion { get; set; }
        public string Id32 { get; set; }
        public string IdPosicion { get; set; }
        public string NumeroOrden33 { get; set; }
        public string Posicion34 { get; set; }
        public string IndicePedidos { get; set; }
        public string CodCuenta { get; set; }
        public string NombreCuenta { get; set; }
        public string CodCentroCosto { get; set; }
        public string NombreCentroCosto { get; set; }
        public string CodProyecto { get; set; }
        public string NombreProyecto { get; set; }
        public string ImporteBruto35 { get; set; }
        public string Neto { get; set; }
        public string Iva36 { get; set; }
        public string CodFiscal37 { get; set; }
        public string PorcentajeIva38 { get; set; }
        public string Cantidad { get; set; }
        public string Texto139 { get; set; }
        public string Texto240 { get; set; }
        public string Texto341 { get; set; }
        public string Texto442 { get; set; }
        public string Texto543 { get; set; }
        public string Texto644 { get; set; }
        public string Texto745 { get; set; }
        public string Texto846 { get; set; }
        public string Texto947 { get; set; }
        public string Texto1048 { get; set; }
        public string Texto11 { get; set; }
        public string Texto12 { get; set; }
        public string Texto13 { get; set; }
        public string Texto14 { get; set; }
        public string Texto15 { get; set; }
        public string Texto16 { get; set; }
        public string Texto17 { get; set; }
        public string Texto18 { get; set; }
        public string Texto19 { get; set; }
        public string Texto20 { get; set; }
        public string Numerico149 { get; set; }
        public string Numerico250 { get; set; }
        public string Numerico351 { get; set; }
        public string Numerico452 { get; set; }
        public string Numerico553 { get; set; }
        public string Fecha154 { get; set; }
        public string Fecha255 { get; set; }
        public string Fecha356 { get; set; }
        public string Fecha457 { get; set; }
        public string Fecha558 { get; set; }
        public string Id59 { get; set; }
        public string NumeroRecepcion { get; set; }
        public string LineaRecepcion { get; set; }
        public string NumeroOrden60 { get; set; }
        public string Posicion61 { get; set; }
        public string CantidadRecibida { get; set; }
        public string Neto62 { get; set; }
        public string PrecioNeto { get; set; }
        public string FechaEntrega { get; set; }
        public string IdUsuario { get; set; }
        public string CodUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string Texto163 { get; set; }
        public string Texto264 { get; set; }
        public string Texto365 { get; set; }
        public string Texto466 { get; set; }
        public string Texto567 { get; set; }
        public string Numerico168 { get; set; }
        public string Numerico269 { get; set; }
        public string Numerico370 { get; set; }
        public string Numerico471 { get; set; }
        public string Numerico572 { get; set; }
        public string Fecha173 { get; set; }
        public string Fecha274 { get; set; }
        public string Fecha375 { get; set; }
        public string Fecha476 { get; set; }
        public string Fecha577 { get; set; }
        public string MetodoRecepcion78 { get; set; }
        public string HistoriaPedidos { get; set; }
        public string nombrearchivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRD_Bitacora> CRD_Bitacora { get; set; }
    }
}
